### PR TITLE
change klog to zap

### PR DESCRIPTION
**Pull request by hdy8200**
**What this PR does / why we need it**:
The previously used Klog function is too simple and not structured, which is inconvenient for us to process and analyze logs at present, so it try to use Zap with more complete functions.

**Which issue this PR fixes** 
 fixes #  the problem of insufficient Klog functions.

**How is this PR tested**
- [ ] unit test
- [ ] e2e test
- [x] other (please specify) 

Use Loki and grafana to collect and view logs in the cluster.

### CODE REVIEW

**Comment by kris21he** [comment]
need go mod tidy? please see the error in CI https://github.com/Edgenesis/shifu/actions/runs/3656080702/jobs/6178112868

**Comment by hdy8200** [comment]
> need go mod tidy? please see the error in CI https://github.com/Edgenesis/shifu/actions/runs/3656080702/jobs/6178112868

**Review by kris21he — APPROVED** [review]
LGTM, seems CI failed with other reason, try re-run the failed ones

**Review by tomqin93 — APPROVED** [review]
LGTM

**Pull request merged**
