### PR TITLE
better doc structure

### PR DESCRIPTION
**Pull request by Yang-Xijie**
**What this PR does / why we need it**:

- remove docs/guide
- add readme in docs
- move docs for users of Shifu to shifu.run

Better doc structure for the open source project.

**Will this PR make the community happier**? Absolutely

**Release note**:

```release-note
move docs for users to shifu.run
```

### CODE REVIEW

**Comment by Yang-Xijie** [comment]
This PR might introduce some broken link because `docs/guide/development` is now moved to `docs/development`, which should be checked.

**Review by tomqin93 — DISMISSED** [review]
LGTM

**Comment by saiyan86** [comment]
LGTM

**Comment by Yang-Xijie** [comment]
> LGTM

@saiyan86 

Sorry but what does the comment LGTM really mean? If this PR is ready to merge, please [approve this PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews#about-pull-request-reviews).

> Approve: Submit feedback and approve merging the changes proposed in the pull request.

**Comment by BtXin** [comment]
> > LGTM
> 
> @saiyan86
> 
> Sorry but what does the comment LGTM really mean? If this PR is ready to merge, please [approve this PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews#about-pull-request-reviews).
> 
> > Approve: Submit feedback and approve merging the changes proposed in the pull request.

LGTM = Look Good To Me

**Review by BtXin — APPROVED** [review]

**Pull request merged**
